import {
  mapRecordFields,
  pickRecordFields,
  SUPPORT_RECORD_FIELDS,
  EMAIL_RECORD_FIELDS,
} from '../../../shared/utils/recordFields.js'

export const ORDER_RECORD_FIELDS = [
  'id',
  'orderNumber',
  'userId',
  'customerName',
  'customerEmail',
  'customerPhone',
  'deliveryNotes',
  'address1',
  'address2',
  'city',
  'state',
  'zip',
  'country',
  'marketingOptIn',
  'saveInfo',
  'status',
  'total',
  'subtotal',
  'shippingMethod',
  'shippingCarrier',
  'shippingService',
  'shippingRateId',
  'shippingRateProvider',
  'shippingAmount',
  'discountAmount',
  'taxAmount',
  'currency',
  'stripePaymentIntentId',
  'createdAt',
  'updatedAt',
]

export function mapAdminOrderRecord(order) {
  if (!order) return null
  return {
    order: pickRecordFields(order, ORDER_RECORD_FIELDS),
    items: mapRecordFields(order.items, [
      'id',
      'orderId',
      'productId',
      'productName',
      'productImage',
      'size',
      'sku',
      'quantity',
      'unitPrice',
      'lineTotal',
      'createdAt',
    ]),
    promoUsage: pickRecordFields(order.promoUsage, [
      'id',
      'promoId',
      'orderId',
      'customerEmail',
      'discountAmount',
      'subtotalAmount',
      'redeemedAt',
    ]),
    campaignUsages: mapRecordFields(order.campaignUsages, [
      'id',
      'orderId',
      'campaignId',
      'donationAmount',
      'eligibleSubtotal',
      'matchedProductIds',
      'createdAt',
      'updatedAt',
    ]),
    statusHistory: mapRecordFields(order.statusHistory, [
      'id',
      'orderId',
      'fromStatus',
      'toStatus',
      'note',
      'changedByType',
      'changedBy',
      'createdAt',
    ]),
    shipments: (order.shipments || []).map((shipment) => ({
      ...pickRecordFields(shipment, [
        'id',
        'orderId',
        'carrier',
        'trackingNumber',
        'trackingUrl',
        'shipmentStatus',
        'estimatedDelivery',
        'shippedAt',
        'deliveredAt',
        'lastSyncedAt',
        'source',
        'createdAt',
        'updatedAt',
      ]),
      events: mapRecordFields(shipment.events, [
        'id',
        'shipmentId',
        'status',
        'message',
        'location',
        'occurredAt',
        'createdAt',
      ]),
    })),
    emailDeliveries: mapRecordFields(
      order.emailDeliveries,
      EMAIL_RECORD_FIELDS,
    ),
    supportRequests: mapRecordFields(
      order.supportRequests,
      SUPPORT_RECORD_FIELDS,
    ),
  }
}
