import {
  getAllPromos,
  getPromoById,
  createPromo,
  updatePromoById,
  deletePromoById,
  validatePromoCode,
  recordPromoUsage,
  normalizePromoCode,
  normalizePromoInput,
  hasReachedUsageLimit,
  expirePromoIfLimitReached,
  isPromoActive,
  calculateDiscountAmount,
} from '../../promos/services/promos.service.js'

export {
  getAllPromos,
  getPromoById,
  createPromo,
  updatePromoById,
  deletePromoById,
  validatePromoCode,
  recordPromoUsage,
  normalizePromoCode,
  normalizePromoInput,
  hasReachedUsageLimit,
  expirePromoIfLimitReached,
  isPromoActive,
  calculateDiscountAmount,
}